- hosts: all
  gather_facts: no
  tasks:
  - name: print the username
    shell: "{{ name }}"
    register: result
  - debug:
      var: result

  - name: working dir
    shell: "{{ pwd }}"
    register: result

  - debug:
      var: result

  - name: Sending an e-mail using Gmail SMTP servers
    mail:
      host: smtp.gmail.com
      port: 465
      username: xxxx
      password: xxxxx
      to: xxxx
      subject: Ansible-report
      body: System {{ ansible_hostname }} has been successfully provisioned.
    delegate_to: localhost

